# Generated by Django 5.2.1 on 2025-06-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_remove_sale_employee_remove_sale_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('name', models.CharField(db_column='tx_name', max_length=70)),
                ('qtdItems', models.IntegerField(db_column='quantity', default=0)),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='tx_name', help_text='Título breve da tarefa (até 70 caracteres)', max_length=70, verbose_name='Título')),
                ('descricao', models.CharField(db_column='tx_descricao', help_text='Detalhes da tarefa (até 200 caracteres)', max_length=200, verbose_name='Descrição')),
            ],
        ),
    ]
