# Generated by Django 5.2.1 on 2025-06-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0005_remove_lista_qtditems_remove_todoitem_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
